apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccountName}}
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::{{.Values.accountId}}:role/{{.Values.serviceAccountName}}-role'
