{{- range .Values.serviceAccountNames }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::{{$.Values.accountId}}:role/{{.}}-role'
{{- end }}